steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app deploy --project=yaron-europecloud-test --quiet


timeout: '1200s'


options:
  logging: 'CLOUD_LOGGING_ONLY'